Add mtls options to aggregate drains.
cloudfoundry/loggregator-agent-release pull request #276
Opened 2023-03-22 21:10 UTC by Benjamintf1

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing performed?

- [x] Unit tests
- [x] Integration tests
- [ ] Acceptance tests

## Checklist:

- [x] This PR is being made against the `main` branch, or relevant version branch
- [ ] I have made corresponding changes to the documentation
- [x] I have added testing for my changes

If you have any questions, or want to get attention for a PR or issue please reach out on the [#logging-and-metrics channel in the cloudfoundry slack](https://cloudfoundry.slack.com/archives/CUW93AF3M)

2023-03-22 21:17 UTC, Benjamintf1 commented
<img width="851" alt="image" src="https://user-images.githubusercontent.com/2761008/227040478-8f307432-7c15-491e-ae1a-6db263a2c073.png">
<img width="620" alt="image" src="https://user-images.githubusercontent.com/2761008/227040543-ee6d980d-a832-47ec-ab53-a4c6a45ae386.png">
<img width="332" alt="image" src="https://user-images.githubusercontent.com/2761008/227040612-80903683-6086-40c4-a979-bf2560890f12.png">
manifest stuff

2023-03-22 21:25 UTC, Benjamintf1 commented
<img width="418" alt="image" src="https://user-images.githubusercontent.com/2761008/227041944-f99d6ab5-2e7e-4c50-bde8-516e18491cf5.png">
Also this, cause have to add client_auth to certificate extended authorities for this version.

Part of me assumes we'd actual generate another cert for the real version with only client perms, but I was being lazy.

2023-03-27 16:02 UTC, chombium requested changes
It looks good, but I think we need few more tests.

Do you think we should also document how the aggregate drains with mTLS will work and can be configured or the syslog-binding-cache job's spec is enough?

2023-03-27 16:02 UTC, chombium commented on jobs/loggr-syslog-binding-cache/templates/aggregate_drains.yml.erb
> +<%
It would be good to add tests for the template as well.

2023-03-27 16:02 UTC, chombium commented on src/pkg/ingress/bindings/aggregate_fetcher_test.go
> +					Url: "syslog://aggregate-drain1.url.com",
Don't we need a test where there are no credentials set?

2023-03-27 16:07 UTC, chombium commented
Hi @Benjamintf1 a part from some small changes I think it looks good. I will do few tests this week as well and will write back.

The one thing that is not clear to me apart from specifying the certs in the binding cache is how one gets everything configured... To setup everything one should create a config file and put the certificate somewhere, so that they get picked up. Should one simply them somewhere, adjust the config and restart the syslog binding cache?

2023-03-27 16:12 UTC, Benjamintf1 commented on jobs/loggr-syslog-binding-cache/templates/aggregate_drains.yml.erb
> +<%
We don't actually run template tests at the moment... D: Like, at all.

2023-03-27 16:13 UTC, Benjamintf1 commented on src/pkg/ingress/bindings/aggregate_fetcher_test.go
> +					Url: "syslog://aggregate-drain1.url.com",
Yeah, probubly. Good call. I was thinking "we've got some no credentials tests in the old suite", but maybe a new suite version would be good too.

2023-03-27 16:17 UTC, Benjamintf1 commented
> Hi @Benjamintf1 a part from some small changes I think it looks good. I will do few tests this week as well and will write back.

> The one thing that is not clear to me apart from specifying the certs in the binding cache is how one gets everything configured... To setup everything one should create a config file and put the certificate somewhere, so that they get picked up. Should one simply them somewhere, adjust the config and restart the syslog binding cache? For usage with cf-d will there be an ops file provided?

Yeah, we should come up with and update the opsfile for cf-deployment for sure. There *does* already exist a aggregate drain opsfile I believe, but it'd have to be modified and or deprecated. 

To get this to work for non-log-cache usecases, I think it'd normally involve adding the certificates to credhub/a vars file and then deploying with those credentials? I'm not sure I understand.

2023-03-27 16:18 UTC, Benjamintf1 commented
As for log-cache, one of us would simply need to make a "make-log-cache-use-mtls" pr which either makes log-cache use mtls, or has a opsfile and deprecates the old regular non-mtls old format agg drain opsfile.

2023-03-27 16:47 UTC, Benjamintf1 commented
(i'll try and make some of these changes friday).

2023-03-28 07:07 UTC, chombium commented on jobs/loggr-syslog-binding-cache/templates/aggregate_drains.yml.erb
> +<%
You can add test for the spec and check if everything is ok in the bpm.yml. Something like in my [PR](https://github.com/cloudfoundry/loggregator-agent-release/pull/187/files#diff-33ba1ba1b045229c48e9617cf3131bbce369784eccdcde952a9d54bc718846fc)

2023-03-31 21:45 UTC, Benjamintf1 commented on jobs/loggr-syslog-binding-cache/templates/aggregate_drains.yml.erb
> +<%
I tested formatting the honestly not so lazy way. I deployed the whole thing both ways.

2023-03-31 22:22 UTC, Benjamintf1 commented
So we didn't get as much work in today as I'd like. 2 open items on this pr.

1) we want to add some more app level tests to syslog_agent mtls suite for aggregate drains.
2) We think we're waiting for some final feedback from you @chombium. We tested it e2e with log-cache and it works great, and that's what you're mainly concerned about if i remember correctly. We will have to figure out how to handle deprecation of the old format of aggregate drains in cf-d when we implement mtls log-cache.

We currently arn't planning on adding spec/rubyspec tests for repo. I understand and appreciate the enthusiasm, we feel like we're adequately covered by our pipeline at the moment for now.

2023-04-03 22:12 UTC, Benjamintf1 commented
Added app tests. Interested in your feedback.

2023-04-07 21:59 UTC, Benjamintf1 commented
https://github.com/cloudfoundry/cf-deployment/pull/1068

cf-d pr

2023-04-11 20:48 UTC, merged

2023-04-13 14:34 UTC, chombium commented
@Benjamintf1 Sorry for the late reply, I have to much on my plate lately :( The change looks good.